# -*- coding: utf-8 -*-
"""Volume_of_Sphere

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OnCBH-Y_qaMhncBeK3dNoE1H0jwlR7eS
"""

def calculate_volume_of_sphere(radius):
  """
  Calculates the volume of a sphere with a given radius.

  Args:
      radius: The radius of the sphere in meters.

  Returns:
      The volume of the sphere in cubic meters.
  """
  from math import pi
  volume = (4/3) * pi * radius**3
  return volume
print (calculate_volume_of_sphere(30))
print (calculate_volume_of_sphere(40))